//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Reactive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Linq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Linq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reactive.Strings_Linq", typeof(Strings_Linq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be called when the scheduler is already running. Try using Sleep instead..
        /// </summary>
        internal static string CANT_ADVANCE_WHILE_RUNNING => "{0} cannot be called when the scheduler is already running. Try using Sleep instead.";
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find event &apos;{0}&apos; on object of type &apos;{1}&apos;..
        /// </summary>
        internal static string COULD_NOT_FIND_INSTANCE_EVENT => "Could not find event '{0}' on object of type '{1}'.";
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find event &apos;{0}&apos; on type &apos;{1}&apos;..
        /// </summary>
        internal static string COULD_NOT_FIND_STATIC_EVENT => "Could not find event '{0}' on type '{1}'.";
        
        /// <summary>
        ///   Looks up a localized string similar to Add method should take 1 parameter..
        /// </summary>
        internal static string EVENT_ADD_METHOD_SHOULD_TAKE_ONE_PARAMETER => "Add method should take 1 parameter.";
        
        /// <summary>
        ///   Looks up a localized string similar to The second parameter of the event delegate must be assignable to &apos;{0}&apos;..
        /// </summary>
        internal static string EVENT_ARGS_NOT_ASSIGNABLE => "The second parameter of the event delegate must be assignable to '{0}'.";
        
        /// <summary>
        ///   Looks up a localized string similar to Event is missing the add method..
        /// </summary>
        internal static string EVENT_MISSING_ADD_METHOD => "Event is missing the add method.";
        
        /// <summary>
        ///   Looks up a localized string similar to Event is missing the remove method..
        /// </summary>
        internal static string EVENT_MISSING_REMOVE_METHOD => "Event is missing the remove method.";
        
        /// <summary>
        ///   Looks up a localized string similar to The event delegate must have a void return type..
        /// </summary>
        internal static string EVENT_MUST_RETURN_VOID => "The event delegate must have a void return type.";
        
        /// <summary>
        ///   Looks up a localized string similar to The event delegate must have exactly two parameters..
        /// </summary>
        internal static string EVENT_PATTERN_REQUIRES_TWO_PARAMETERS => "The event delegate must have exactly two parameters.";
        
        /// <summary>
        ///   Looks up a localized string similar to Remove method should take 1 parameter..
        /// </summary>
        internal static string EVENT_REMOVE_METHOD_SHOULD_TAKE_ONE_PARAMETER => "Remove method should take 1 parameter.";
        
        /// <summary>
        ///   Looks up a localized string similar to The first parameter of the event delegate must be assignable to &apos;{0}&apos;..
        /// </summary>
        internal static string EVENT_SENDER_NOT_ASSIGNABLE => "The first parameter of the event delegate must be assignable to '{0}'.";
        
        /// <summary>
        ///   Looks up a localized string similar to Remove method of a WinRT event should take an EventRegistrationToken..
        /// </summary>
        internal static string EVENT_WINRT_REMOVE_METHOD_SHOULD_TAKE_ERT => "Remove method of a WinRT event should take an EventRegistrationToken.";
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one element..
        /// </summary>
        internal static string MORE_THAN_ONE_ELEMENT => "Sequence contains more than one element.";
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one matching element..
        /// </summary>
        internal static string MORE_THAN_ONE_MATCHING_ELEMENT => "Sequence contains more than one matching element.";
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no elements..
        /// </summary>
        internal static string NO_ELEMENTS => "Sequence contains no elements.";
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no matching element..
        /// </summary>
        internal static string NO_MATCHING_ELEMENTS => "Sequence contains no matching element.";
    }
}