//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Reactive
{
    using System.Reflection;

    internal class Strings_WindowsThreading
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Strings_WindowsThreading()
        {
        }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "System.Reactive.Platforms.Windows.Strings_WindowsThreading",
                        typeof(Strings_WindowsThreading).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string NO_DISPATCHER_CURRENT_THREAD => "The current thread has no Dispatcher associated with it.";

        internal static string NO_WINDOW_CURRENT => "No current Window object found to obtain a CoreDispatcher from.";
    }
}